### ISSUE TITLE
Miscellaneous TODO

### ISSUE THREAD

**Issue by SailingSteve** [wevote/EndorsementExtension#62]
- [ ] Add ability to logout
- [ ] Does Send us a comment about this page: work?
- [ ] Display a default organization icon if we don't receive one.  (https://www.sierraclub.org/california/2020-endorsements)
- [ ]

**Comment by SailingSteve** [comment]
Logout is workiong, send is working
