### ISSUE TITLE
TODO: May 2020

### ISSUE THREAD

**Issue by SailingSteve** [wevote/EndorsementExtension#72]
- [x] If a PDF exists for the year, load it instead of making a new one
- [x] Extension crashes out with no warning after editing and updating a candidate position in the right pane.
- [x] The WebApp page and my page are referring to different data.
<img width="880" alt="Screen Shot 2020-04-18 at 2 19 09 PM" src="https://user-images.githubusercontent.com/6923653/79671536-a35f8f80-817f-11ea-9c3e-3e0b53dd5791.png">

- [x] Delete from editor does not work anymore, need it to test yellows in the pane
- [x] Close dialog initiated from WebApp in the frame, does not work.
- [x] Fix "too big button" in html from PDFs
- [x] Make PDFs expire in a year, instead of a week

**Comment by SailingSteve** [comment]
@DaleMcGrew The todo list based on today's discussion

**Comment by SailingSteve** [comment]
https://www.npmjs.com/package/pdf2html  needs a java jre and runs in node only
