### ISSUE TITLE
TODO: Dec 2020

### ISSUE THREAD

**Issue by SailingSteve** [wevote/EndorsementExtension#84]
- [ ] All that voter oriented stuff is slowing down the expert stuff
- [ ] Sometimes: Crazy slow opening of pop-up, and crazy slow response to "Open edit panel for this tab"
- [ ] Close of the dialog with iframe to the webapp, fails to update the rightPositionPanes.  I think it is related to the passed values of voterGuidePossibilityId, positionWeVoteId, & possibilityPositionId

Less:
- [ ] Does not eliminate duplicate names on https://atlinq.com/atlanta-inquirer-endorsements-for-georgia-elections/
- [ ] Server side: use the auto scanning code in the server (https://api.wevoteusa.org/vg/possibility_list/ View Details button) to "Scan Voter Guide" for a first pass at getting all of the endorsements on the page into the db. (and on the editor pane in the chrome extension).
- [ ] wevote/WeVoteServer/issues/1254  Integrate the new PDF scanner code into Admin Voter Guide Possibility Scanner
- [x] Painfully slow load of WebApp, 
- [x] Disable load of stripe and zendesk

**Comment by SailingSteve** [comment]
These have been resolved or are no longer relevant

**Comment by SailingSteve** [comment]
These have been resolved or are no longer relevant
